INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): discordapp.com
DEBUG:requests.packages.urllib3.connectionpool:"GET /api/v6/gateway HTTP/1.1" 200 35
INFO:GatewayClient:Opening websocket connection to URL `wss://gateway.discord.gg?v=6&encoding=json`
INFO:GatewayClient:WS Opened: sending identify payload
INFO:GatewayClient:Recieved HELLO, starting heartbeater...
INFO:GatewayClient:Recieved READY
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/gevent/greenlet.py", line 536, in run
    result = self._run(*self.args, **self.kwargs)
  File "/usr/lib/python3.6/site-packages/holster/emitter.py", line 63, in _call
    func(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/holster/emitter.py", line 39, in __call__
    return self.func(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/disco/gateway/client.py", line 147, in on_error
    raise Exception('WS recieved error: %s', error)
Exception: ('WS recieved error: %s', WebSocketConnectionClosedException('Connection is already closed.',))
Tue Jan 17 22:57:52 2017 <Greenlet at 0x7f43b0c6a340: <bound method Emitter._call of <holster.emitter.Emitter object at 0x7f43b0c477b8>>(<holster.emitter.EmitterSubscription object at 0x7, (WebSocketConnectionClosedException('Connection is, {})> failed with Exception

INFO:GatewayClient:WS Closed: [None] None (1)
INFO:GatewayClient:Will attempt to resume after 5 seconds
INFO:GatewayClient:Opening websocket connection to URL `wss://gateway.discord.gg?v=6&encoding=json`
INFO:GatewayClient:WS Opened: attempting resume w/ SID: bd34e3fee243f93380b633d652d674c2 SEQ: 17
INFO:GatewayClient:Recieved HELLO, starting heartbeater...
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): discordapp.com
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/gevent/greenlet.py", line 536, in run
    result = self._run(*self.args, **self.kwargs)
  File "/usr/lib/python3.6/site-packages/holster/emitter.py", line 63, in _call
    func(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/holster/emitter.py", line 39, in __call__
    return self.func(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/disco/gateway/client.py", line 147, in on_error
    raise Exception('WS recieved error: %s', error)
Exception: ('WS recieved error: %s', WebSocketConnectionClosedException('Connection is already closed.',))
Tue Jan 17 22:57:59 2017 <Greenlet at 0x7f43b0c6af20: <bound method Emitter._call of <holster.emitter.Emitter object at 0x7f43b0153940>>(<holster.emitter.EmitterSubscription object at 0x7, (WebSocketConnectionClosedException('Connection is, {})> failed with Exception

INFO:GatewayClient:WS Closed: [None] None (2)
INFO:GatewayClient:Will attempt to resume after 10 seconds
DEBUG:requests.packages.urllib3.connectionpool:"POST /api/v6/channels/191749825082032134/messages HTTP/1.1" 200 None
INFO:GatewayClient:Opening websocket connection to URL `wss://gateway.discord.gg?v=6&encoding=json`
INFO:GatewayClient:WS Opened: attempting resume w/ SID: bd34e3fee243f93380b633d652d674c2 SEQ: 25
INFO:GatewayClient:Recieved HELLO, starting heartbeater...
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): discordapp.com
DEBUG:requests.packages.urllib3.connectionpool:"POST /api/v6/channels/191749825082032134/messages HTTP/1.1" 200 None
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/gevent/greenlet.py", line 536, in run
    result = self._run(*self.args, **self.kwargs)
  File "/usr/lib/python3.6/site-packages/holster/emitter.py", line 63, in _call
    func(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/holster/emitter.py", line 39, in __call__
    return self.func(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/disco/gateway/client.py", line 147, in on_error
    raise Exception('WS recieved error: %s', error)
Exception: ('WS recieved error: %s', WebSocketConnectionClosedException('Connection is already closed.',))
Tue Jan 17 22:58:12 2017 <Greenlet at 0x7f43b0c6ae88: <bound method Emitter._call of <holster.emitter.Emitter object at 0x7f43b00f1f98>>(<holster.emitter.EmitterSubscription object at 0x7, (WebSocketConnectionClosedException('Connection is, {})> failed with Exception

INFO:GatewayClient:WS Closed: [None] None (3)
INFO:GatewayClient:Will attempt to resume after 15 seconds
KeyboardInterrupt
Tue Jan 17 22:58:13 2017
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.6/site-packages/disco/cli.py", line 81, in <module>
    disco_main(True)
  File "/usr/lib/python3.6/site-packages/disco/cli.py", line 76, in disco_main
    (bot or client).run_forever()
  File "/usr/lib/python3.6/site-packages/disco/bot/bot.py", line 419, in run_forever
    self.client.run_forever()
  File "/usr/lib/python3.6/site-packages/disco/client.py", line 134, in run_forever
    return self.gw.run()
  File "/usr/lib/python3.6/site-packages/disco/gateway/client.py", line 205, in run
    self.ws_event.wait()
  File "/usr/lib/python3.6/site-packages/gevent/event.py", line 219, in wait
    return self._wait(timeout)
  File "/usr/lib/python3.6/site-packages/gevent/event.py", line 129, in _wait
    gotit = self._wait_core(timeout)
  File "/usr/lib/python3.6/site-packages/gevent/event.py", line 106, in _wait_core
    result = self.hub.switch()
  File "/usr/lib/python3.6/site-packages/gevent/hub.py", line 630, in switch
    return RawGreenlet.switch(self)
KeyboardInterrupt
